version: "3"
services:
  db_aurora_store_3:
    container_name: db_aurora_store_3
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: "no"
    environment:
      MYSQL_DATABASE: aurora_store
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  redis_aurora_store_3:
    container_name: redis_aurora_store_3
    image: redis
    command: redis-server
    ports:
      - "6378:6379"
